version: 2.1
setup: true
orbs:
  orb-tools: circleci/orb-tools@12.0
  shellcheck: circleci/shellcheck@3.1
  aws-cli: circleci/aws-cli@5.1.0
  aws-ecr: circleci/aws-ecr@9.3.2
filters: &filters
  tags:
    only: /.*/
jobs:
  build-test-then-push-with-buildx:
    machine:
      image: ubuntu-2204:current
    parameters:
      repo:
        type: string
      tag:
        type: string
      dockerfile:
        type: string
      platform:
        type: string
      region:
        type: string
    steps:
      - checkout
      - aws-cli/setup:
          role_arn: arn:aws:iam::122211685980:role/CPE_ECR_OIDC_TEST
          profile_name: "default" 
          role_session_name: ecr-orb-test-session-buildx
          region: "us-west-2"
      - aws-ecr/ecr_login:
          profile_name: default
          region: "us-west-2"
          account_id: "122211685980"
          use_credentials_helper: false
      - aws-ecr/build_image:
          repo: << parameters.repo >>
          tag: << parameters.tag >>
          dockerfile: << parameters.dockerfile >>
          platform: << parameters.platform >>
          push_image: true
workflows:
  lint-pack:
    jobs:
      - build-test-then-push-with-buildx:
          repo: aws-ecr-orb-tempora-test
          context: [CPE-OIDC]
          tag: temporal-test
          dockerfile: sample/Dockerfile
          platform: linux/amd64
          region: us-west-2
          filters: *filters
      - orb-tools/lint:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/review:
          filters: *filters
      - shellcheck/check:
          filters: *filters
      # Triggers the next workflow in the Orb Development Kit.
      # - orb-tools/continue:
      #     orb_name: aws-ecr
      #     pipeline_number: << pipeline.number >>
      #     vcs_type: << pipeline.project.type >>
      #     requires: [orb-tools/lint, orb-tools/review, orb-tools/pack, shellcheck/check, ]
      #     filters: *filters
